variables:
    ArmTemplateRoot: '$(Build.SourcesDirectory)\Resources\ArmTemplates'
    SolutionBaseName: 'Dfc.FutureAccessModel.Shared'

resources:
  repositories:
  - repository: self
  - repository: dfc-devops
    type: github
    name: SkillsFundingAgency/dfc-devops
    ref: refs/tags/v1.9.1
    endpoint: 'GitHub (ESFA)'

stages:
- stage: Build
  displayName: Test and Publish ARM Template
  jobs:
  - job: TestAndPublish
    pool:
      name: NCS - CI and CD
    steps:
    - template: AzureDevOpsTemplates/Build/StepTemplates/dfc-arm-build.yml@dfc-devops
      parameters:
        ArmTemplateRoot: $(ArmTemplateRoot)
        SolutionBaseName: $(SolutionBaseName)
        PublishPipelineArtifact: true

- stage: DeployTo_DEV
  displayName: Deploy ARM resources to DEV_FUTUREACCESSMODEL environment
  variables:
  - group: dfc-shared-all
  - group: dfc-futureaccessmodel-shared-all
  - group: dfc-shared-dev
  - group: dfc-futureaccessmodel-shared-dev
  - template: VariableTemplates\DevEnvironmentVariables.yml
  jobs:
  - deployment: DeployTo_DEV
    pool:
      name: 'NCS - CI and CD'
    environment: DEV_FUTUREACCESSMODEL
    strategy:
      runOnce:
        deploy:
          steps:
          - template: AzureDevOpsTemplates/Deploy/StepTemplates/dfc-arm-deploy.yml@dfc-devops
            parameters:
              ArmTemplateRoot: '$(Pipeline.Workspace)/Dfc.FutureAccessModel.Shared.Resources.ArmTemplates'
              AzureSubscription: 'SFA-CDH-Dev/Test (962cae10-2950-412a-93e3-d8ae92b17896)'
              EnvironmentTag: $(EnvironmentTag)
              ParentBusinessTag: $(ParentBusiness)
              ResourceGroup: $(famSharedResourceGroup)
              ServiceOfferingTag: $(ServiceOffering)

- stage: DeployTo_SIT
  displayName: Deploy ARM resources to SIT_FUTUREACCESSMODEL environment
  variables:
  - group: dfc-shared-all
  - group: dfc-futureaccessmodel-shared-all
  - group: dfc-shared-sit
  - group: dfc-futureaccessmodel-shared-sit
  - template: VariableTemplates\SitEnvironmentVariables.yml
  jobs:
  - deployment: DeployTo_SIT
    pool:
      name: 'NCS - CI and CD'
    environment: SIT_FUTUREACCESSMODEL
    strategy:
      runOnce:
        deploy:
          steps:
          - template: AzureDevOpsTemplates/Deploy/StepTemplates/dfc-arm-deploy.yml@dfc-devops
            parameters:
              ArmTemplateRoot: '$(Pipeline.Workspace)/Dfc.FutureAccessModel.Shared.Resources.ArmTemplates'
              AzureSubscription: 'SFA-CDH-Dev/Test (962cae10-2950-412a-93e3-d8ae92b17896)'
              EnvironmentTag: $(EnvironmentTag)
              ParentBusinessTag: $(ParentBusiness)
              ResourceGroup: $(famSharedResourceGroup)
              ServiceOfferingTag: $(ServiceOffering)
