variables:
- name: ArmTemplateRoot
  value: '$(Build.SourcesDirectory)\Resources\ArmTemplates'
- name: SolutionBaseName
  value: 'Dfc.FutureAccessModel.Shared'
- group: dfc-shared-all
- group: dfc-futureaccessmodel-shared-all

resources:
  repositories:
  - repository: self
  - repository: DfcDevops
    type: github
    name: SkillsFundingAgency/dfc-devops
    ref: refs/tags/v1.9.1
    endpoint: 'GitHub (ESFA)'

stages:
- stage: Build
  displayName: Test and Publish ARM Template
  jobs:
  - job: TestAndPublish
    pool:
      name: NCS - CI and CD
    steps:
    - template: AzureDevOpsTemplates/Build/StepTemplates/dfc-arm-build.yml@DfcDevops
      parameters:
        ArmTemplateRoot: $(ArmTemplateRoot)
        SolutionBaseName: $(SolutionBaseName)
        PublishPipelineArtifact: true

- stage: DeployTo_DEV
  displayName: Deploy ARM resources to DEV_FUTUREACCESSMODEL environment
  condition: ne(succeeded(), variables['Build.Reason'], 'PullRequest')
  variables:
  - group: dfc-shared-dev
  - group: dfc-futureaccessmodel-shared-dev
  - template: VariableTemplates\DevEnvironmentVariables.yml
  jobs:
  - template: JobTemplates/Deploy.yml
    parameters:
      AzureSubscription: 'SFA-CDH-Dev/Test (962cae10-2950-412a-93e3-d8ae92b17896)'
      CosmosDbAccountName: $(famSharedCosmosAccount)
      Environment: DEV_FUTUREACCESSMODEL

- stage: DeployTo_SIT
  displayName: Deploy ARM resources to SIT_FUTUREACCESSMODEL environment
  condition: ne(succeeded(), variables['Build.Reason'], 'PullRequest')
  variables:
  - group: dfc-shared-sit
  - group: dfc-futureaccessmodel-shared-sit
  - template: VariableTemplates\SitEnvironmentVariables.yml
  jobs:
  - template: JobTemplates/Deploy.yml
    parameters:
      AzureSubscription: 'SFA-CDH-Dev/Test (962cae10-2950-412a-93e3-d8ae92b17896)'
      CosmosDbAccountName: $(famSharedCosmosAccount)
      Environment: SIT_FUTUREACCESSMODEL
